name: Mélodium on Mac OS Workflow

on:
  workflow_call:
    inputs:
      command:
        type: string
        required: false
        default: run .melodium-ci/Compo.toml
        description: 'The Mélodium command to run'
      version:
        type: string
        required: false
        default: 0.9.2
        description: 'The Mélodium version to use (should usually be the same as the workflow)'

      repository:
        type: string
        required: false
        description: '_From actions/checkout@v4_ Repository name with owner. For example, actions/checkout'
        default: ${{ github.repository }}
      ref:
        type: string
        required: false
        description: >
          _From actions/checkout@v4_ The branch, tag or SHA to checkout. When checking out the repository that
          triggered a workflow, this defaults to the reference or SHA for that
          event.  Otherwise, uses the default branch.
      ssh-key:
        type: string
        description: >
          _From actions/checkout@v4_ SSH key used to fetch the repository. The SSH key is configured with the local
          git config, which enables your scripts to run authenticated git commands.
          The post-job step removes the SSH key.


          We recommend using a service account with the least permissions necessary.


          [Learn more about creating and using
          encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
      ssh-known-hosts:
        type: string
        description: >
          _From actions/checkout@v4_ Known hosts in addition to the user and global host key database. The public
          SSH keys for a host may be obtained using the utility `ssh-keyscan`. For example,
          `ssh-keyscan github.com`. The public key for github.com is always implicitly added.
      ssh-strict:
        type: boolean
        description: >
          _From actions/checkout@v4_ Whether to perform strict host key checking. When true, adds the options `StrictHostKeyChecking=yes`
          and `CheckHostIP=no` to the SSH command line. Use the input `ssh-known-hosts` to
          configure additional hosts.
        default: true
      ssh-user:
        type: string
        description: >
          _From actions/checkout@v4_ The user to use when connecting to the remote SSH host. By default 'git' is used.
        default: git
      persist-credentials:
        type: boolean
        description: '_From actions/checkout@v4_ Whether to configure the token or SSH key with the local git config'
        default: true
      path:
        type: string
        description: '_From actions/checkout@v4_ Relative path under $GITHUB_WORKSPACE to place the repository'
      clean:
        type: boolean
        description: '_From actions/checkout@v4_ Whether to execute `git clean -ffdx && git reset --hard HEAD` before fetching'
        default: true
      filter:
        type: string
        required: false
        description: >
          _From actions/checkout@v4_ Partially clone against a given filter.
          Overrides sparse-checkout if set.
      sparse-checkout:
        type: string
        required: false
        description: >
          _From actions/checkout@v4_ Do a sparse checkout on given patterns.
          Each pattern should be separated with new lines.
      sparse-checkout-cone-mode:
        type: boolean
        description: >
          _From actions/checkout@v4_ Specifies whether to use cone-mode when doing a sparse checkout.
        default: true
      fetch-depth:
        type: number
        description: '_From actions/checkout@v4_ Number of commits to fetch. 0 indicates all history for all branches and tags.'
        default: 1
      fetch-tags:
        type: boolean
        description: '_From actions/checkout@v4_ Whether to fetch tags, even if fetch-depth > 0.'
        default: false
      show-progress:
        type: boolean
        description: '_From actions/checkout@v4_ Whether to show progress status output when fetching.'
        default: true
      lfs:
        type: boolean
        description: '_From actions/checkout@v4_ Whether to download Git-LFS files'
        default: false
      submodules:
        type: boolean
        description: >
          _From actions/checkout@v4_ Whether to checkout submodules: `true` to checkout submodules or `recursive` to
          recursively checkout submodules.


          When the `ssh-key` input is not provided, SSH URLs beginning with `git@github.com:` are
          converted to HTTPS.
        default: false
      set-safe-directory:
        type: boolean
        description: _From actions/checkout@v4_ Add repository path as safe.directory for Git global config by running `git config --global --add safe.directory <path>`
        default: true
      github-server-url:
        type: boolean
        description: _From actions/checkout@v4_ The base URL for the GitHub instance that you are trying to clone from, will use environment defaults to fetch from the same instance that the workflow is running from unless specified. Example URLs are https://github.com or https://my-ghes-server.example.com
        required: false
      
      artifact-name:
        type: string
        description: '_From actions/upload-artifact@v4_ Artifact name'
        default: 'artifact'
        required: false
      artifact-path:
        type: string
        description: '_From actions/upload-artifact@v4_ A file, directory or wildcard pattern that describes what to upload'
        required: true
        default: ''
      artifact-if-no-files-found:
        type: string
        description: >
          _From actions/upload-artifact@v4_ The desired behavior if no files are found using the provided path.

          Available Options:
            warn: Output a warning but do not fail the action
            error: Fail the action with an error message
            ignore: Do not output any warnings or errors, the action does not fail
        default: 'warn'
      artifact-retention-days:
        type: number
        description: >
          _From actions/upload-artifact@v4_ Duration after which artifact will expire in days. 0 means using default retention.

          Minimum 1 day.
          Maximum 90 days unless changed from the repository settings page.
      artifact-compression-level:
        type: number
        description: >
          _From actions/upload-artifact@v4_ The level of compression for Zlib to be applied to the artifact archive.
          The value can range from 0 to 9:
          - 0: No compression
          - 1: Best speed
          - 6: Default compression (same as GNU Gzip)
          - 9: Best compression
          Higher levels will result in better compression, but will take longer to complete.
          For large files that are not easily compressed, a value of 0 is recommended for significantly faster uploads.
        default: 6
      artifact-overwrite:
        type: boolean
        description: >
          _From actions/upload-artifact@v4_ If true, an artifact with a matching name will be deleted before a new one is uploaded.
          If false, the action will fail if an artifact for the given name already exists.
          Does not fail if the artifact does not exist.
        default: false
      artifact-include-hidden-files:
        type: boolean
        description: >
          _From actions/upload-artifact@v4_ If true, hidden files will be included in the artifact.
          If false, hidden files will be excluded from the artifact.
        default: false

    secrets:
      github-token:
        required: true
        description: >
          _From actions/checkout@v4_ Personal access token (PAT) used to fetch the repository. The PAT is configured
          with the local git config, which enables your scripts to run authenticated git
          commands. The post-job step removes the PAT.


          We recommend using a service account with the least permissions necessary.
          Also when generating a new PAT, select the least scopes necessary.


          [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
      melodium-token:
        required: false
        description: >
          Mélodium API Token
      secret-1:
        required: false
      secret-2:
        required: false
      secret-3:
        required: false
      secret-4:
        required: false
      secret-5:
        required: false
      secret-6:
        required: false
      secret-7:
        required: false
      secret-8:
        required: false
      secret-9:
        required: false
      secret-10:
        required: false

jobs:
  melodium:
    runs-on: macos-latest
    steps:
      - name: Setup Mélodium
        run: |
          curl --silent --show-error --output /tmp/melodium.sh "https://repo.melodium.tech/install/${{ inputs.version }}/melodium-${{ inputs.version }}_aarch64-apple-darwin.sh"
          chmod +x /tmp/melodium.sh
          sudo /tmp/melodium.sh
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}
          token: ${{ secrets.github-token }}
          ssh-key: ${{ inputs.ssh-key }}
          ssh-known-hosts: ${{ inputs.ssh-known-hosts }}
          ssh-strict: ${{ inputs.ssh-strict }}
          ssh-user: ${{ inputs.ssh-user }}
          persist-credentials: ${{ inputs.persist-credentials }}
          path: ${{ inputs.path }}
          clean: ${{ inputs.clean }}
          filter: ${{ inputs.filter }}
          sparse-checkout: ${{ inputs.sparse-checkout }}
          sparse-checkout-cone-mode: ${{ inputs.sparse-checkout-cone-mode }}
          fetch-depth: ${{ inputs.fetch-depth }}
          fetch-tags: ${{ inputs.fetch-tags }}
          show-progress: ${{ inputs.show-progress }}
          lfs: ${{ inputs.lfs }}
          submodules: ${{ inputs.submodules }}
      - name: Run Mélodium
        run: melodium ${{ inputs.command }}
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
          MELODIUM_TOKEN: ${{ secrets.melodium-token }}
          SECRET_1: ${{ secrets.secret-1 }}
          SECRET_2: ${{ secrets.secret-2 }}
          SECRET_3: ${{ secrets.secret-3 }}
          SECRET_4: ${{ secrets.secret-4 }}
          SECRET_5: ${{ secrets.secret-5 }}
          SECRET_6: ${{ secrets.secret-6 }}
          SECRET_7: ${{ secrets.secret-7 }}
          SECRET_8: ${{ secrets.secret-8 }}
          SECRET_9: ${{ secrets.secret-9 }}
          SECRET_10: ${{ secrets.secret-10 }}
      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}
          if-no-files-found: ${{ inputs.artifact-if-no-files-found }}
          retention-days: ${{ inputs.artifact-retention-days }}
          compression-level: ${{ inputs.artifact-compression-level }}
          overwrite: ${{ inputs.artifact-overwrite }}
          include-hidden-files: ${{ inputs.artifact-include-hidden-files }}